name: Siamese_Network
channels:
  - conda-forge
  - pytorch
dependencies:
  - python==3.6.1
  - opencv
  - matplotlib
  - pytorch
  - torchvision
  - cudatoolkit=10.0
  - pip
  - pip:
    - tensorboardx==1.6
