name: Siamese_Network
channels:
  - conda-forge
  - pytorch
dependencies:
  - python==3.6.1
  - opencv
  - matplotlib=2.0.2
  - pytorch=1.0.1
  - torchvision=0.2.2
  - cudatoolkit=10.0
  - absl-py=0.7.1
  - pip=9.0.1
  - pip:
    - tensorboardx==1.6
